chore: support for partialFilterExpressions in indexes
chore: fix compilation errors

chore: improve pre-commit hook so it checks also for compilation issues

chore: fix redundant nullable type

diff --git a/gradle/pre-commit b/gradle/pre-commit
--- a/gradle/pre-commit
+++ b/gradle/pre-commit
@@ -1,30 +1,43 @@
 #!/bin/bash
+
 echo "*********************************************************"
-echo "Running git pre-commit hook. Running KtLint... "
+echo "Running git pre-commit hook. "
 echo "*********************************************************"
+
+export BUILD_SEGMENT_API_KEY=0
+endStatus=0
 
 # Gather the staged files - to make sure changes are saved only for these files.
 stagedFiles=$(git diff --staged --name-only)
+
+# check if everything compiles
+./gradlew --quiet compileKotlin compileTestKotlin
+
+status=$?
+((endStatus+=status))
+
+if [ "$status" = 0 ] ; then
+    echo "🟢 Project compiled successfully."
+else
+    echo 1>&2 "🔴 Project could not be compiled."
+fi
 
 # run ktlint apply
 ./gradlew --quiet ktlintFormat
 
 status=$?
+((endStatus+=status))
 
 if [ "$status" = 0 ] ; then
-    echo "Static analysis found no problems."
+    echo "🟢 KtLint found no issues."
     # Add staged file changes to git
     for file in $stagedFiles; do
       if test -f "$file"; then
         git add "$file"
       fi
     done
-    #Exit
-    exit 0
 else
-    echo "*********************************************************"
-    echo 1>&2 "KtLint found violations it could not fix."
-    echo "*********************************************************"
-    #Exit
-    exit 1
+    echo 1>&2 "🔴 KtLint found violations it could not fix."
 fi
+
+exit $endStatus
